### ISSUE TITLE
Feature Request: Option to sort tokens in rescue hud alphabetically

### ISSUE THREAD

**Issue by esheyw** [xaukael/covered-token-rescue-hud#10]
I'm the one who originally supplied the GIF you've got in the readme now (happy to! selling people on this module is easier with an example!), and while I was making it I found it annoying that things were ordered by their stacking and not by name. If I have tokens
```
       A
 B, C, D, E
 ```
 I'd like to swap to C, then back to A, and have it return to the same ordering I started with.

**Comment by xaukael** [comment]
I have no way of determining that without storing the previous state somewhere. This module does not actually modify the stack in any direct way.

**Comment by esheyw** [comment]
That would be the consequence of the ask in the title, no? just alpha sort the tokens in the hud by token name?

**Comment by xaukael** [comment]
Right you are. Your example confused and distracted me from the title. I put name sorting in this morning and it seems to be working okay, I will do a version release after work.
