### ISSUE TITLE
Feature Request: target using small element

### ISSUE THREAD

**Issue by dirusulixes** [xaukael/covered-token-rescue-hud#11]
When the small element is selected I'd like to be able to target the represented token instead of the one at the top of the pile.

**Comment by xaukael** [comment]
I am not sure what you are asking for.

right click to bring up the hud, then click the target

**Comment by uniwars** [comment]
I think he means hvoering the miniature token and press "t" for target, which I +1

**Comment by xaukael** [comment]
Unfortunately, I cannot make it behave this way both because of how core keybinds work and how events are processed on html elements. The right click for HUD is the best I can do.
