### ISSUE TITLE
Feature Request: Allow token click actions

### ISSUE THREAD

**Issue by ckdragons** [xaukael/covered-token-rescue-hud#12]
Currently, we can click on the small icon to show the covered token's HUD. Possible to add the double left- and right-clicks to open the hidden token's actor sheet and token property windows?

**Comment by xaukael** [comment]
I can add the double click for the actor sheet. I will put that in the next release. I cannot do the right click. Right click currently brings up the hud and when the hud is rendered for a hidden token, the rescue hud is removed so a second click is not possible. 

A simply work around is to right click to bring up the hud for the token, then click the gear icon for the token configuration. It is the same number of clicks either way.
