### ISSUE TITLE
Bug: the character's name plate covers the hit point field

### ISSUE THREAD

**Issue by ckdragons** [xaukael/covered-token-rescue-hud#13]
![image](https://user-images.githubusercontent.com/84493092/227701568-b916cc06-e34f-4055-b58d-fe158e377266.png)

**Comment by xaukael** [comment]
I am not sure how you managed that, but I cannot reproduce. Can you describe the steps to make this happen?

**Comment by ckdragons** [comment]
Right-clicked on the hidden token's icon to bring up the HUD. In the picture, the icon showing is for Nora (PC) and Chumley (PC) is hidden underneath.

**Comment by xaukael** [comment]
fixed by removing the tooltip
