### ISSUE TITLE
v11 Compatibility?

### ISSUE THREAD

**Issue by esheyw** [xaukael/covered-token-rescue-hud#14]
The module seems mostly non-functional in v11. I'm not getting any warnings or errors, and the sub-token icons are there, but they're non-interactable. foundry 11.302, pf2e 5.0.2.
![](https://i.imgur.com/9daw6Co.gif)

**Comment by xaukael** [comment]
Change in foundry's style.css broke the events. It is fixed now and I bumped the module compatibility to v11.

**Comment by esheyw** [comment]
Quick initial testing shows it working. Thanks for the very quick turnaround!
