### ISSUE TITLE
Bug?: Hovering the HUD tokens produces incorrect grid border highlight

### ISSUE THREAD

**Issue by esheyw** [xaukael/covered-token-rescue-hud#15]
![](https://i.imgur.com/ICehmcD.gif)
Hovering the rescue HUD tokens highlights the grid space as if the token disposition was enemy, not party.

**Comment by esheyw** [comment]
Also I just noticed the initial HUD there was including the topmost token, and not one of the others 🤔

**Comment by xaukael** [comment]
The highlight is always red and has nothing to do with the disposition of the token. I should probably make that a different color or white so that it does not confuse in this way. 

It should not include the token being hovered. That is odd. Are you on Foundry v10 or v11?

**Comment by esheyw** [comment]
11.304, pf2e 5.0.2. I'll do more testing on that and open a separate issue if I can get it to reliably happen when I do some testing after work this evening.

**Comment by xaukael** [comment]
I changed the hover highlight border to be a dotted white as to not be confused with an enemy border.

**Comment by esheyw** [comment]
much clearer! ty.
