### ISSUE TITLE
Typo in line 19

### ISSUE THREAD

**Issue by saint-thomas-more** [xaukael/covered-token-rescue-hud#18]
I believe it should be `t.h` instead of `t.w` at the end.
`let bottomRight2 = { x: t.x + t.w , y: t.y + t.h };`
https://github.com/xaukael/covered-token-rescue-hud/blob/cbb2d982196544a98f0c425264e5696b8065e5db/covered-token-rescue-hud.js#L19

**Comment by xaukael** [comment]
fixed in 1.0.12
