### ISSUE TITLE
[Bug] Uknown exception "Error: Syntax error, unrecognized expression: unsupported pseudo: hover"

### ISSUE THREAD

**Issue by p4535992** [xaukael/covered-token-rescue-hud#2]
I get it this exception when i try to use the module

![img](https://i.imgur.com/MAGzEjc.png)

**Comment by xaukael** [comment]
fixed in 1.0.2

**Comment by xaukael** [comment]
seems there is some inconsistency in what check for hover jquery will accept. The fix I put in place fixes it with no other modules enabled, but with some of my other modules enabled, it seems to like the old way and hates the new one. Not sure what to do.

**Comment by p4535992** [comment]
Work like a charm now on my world. Ty very much
