### ISSUE TITLE
[Feature Request] Possibility of moving the rescued token. Via small token?

### ISSUE THREAD

**Issue by Fridan99** [xaukael/covered-token-rescue-hud#5]
When there is one token overlapping another, and you try to rescue the hidden token, if you try to move it, the token on top of it moves, but not the rescued.

Example..... The undead dwarf is on top... if i try to move to another space, i can move it. 
![22](https://user-images.githubusercontent.com/86131373/216727693-e9e9accc-cbee-44cd-9e0a-2c6494dd8ddc.jpg)

Example 2..... When i rescue the token behind the undead dwarf (the blonde girl), if i try to move it, the bottom token is moved (undead dwarf), therefore there is no possibility to move the rescued token (the blonde girl), if not first by moving the unrescued token. 
![1](https://user-images.githubusercontent.com/86131373/216727839-101ab2d5-5c94-4340-ac4c-3804b70ce438.jpg)

Perhaps if the possibility to move the rescued token from the small token was implemented, it could be a possibility.  

Undead dwarf is an NPC actor.

Blonde girl is a linked actor PC. 

BTW, the module is great.

**Comment by xaukael** [comment]
I think if you click the mock token, it should control that token and thus bring it to top to drag if it is at the same elevation and use the arrow keys or wasd to move the token if it is at a lower elevation. Making the tiny token draggable could be done, but I expect how I would have to implement it could potentially have many module conflicts.

**Comment by Fridan99** [comment]
Right. I have deactivated all modules, activated only token rescue, and yes you can move both tokens. So it must be some kind of conflict with some other module, which causes that only the bottom token can be moved, but the other no.

I'm going to try and see which module is causing this little problem. 

ok, I have finally figured out which module creates this problem. Token Z module. 

If you have z token and a rescue token modules active, you cannot move both tokens. only 1 of them. 

I think both modules do exactly the same thing, so I don't think it's a question of choosing one or the other.

You can probably close this thread, if you find it convenient.    :)

**Comment by Fridan99** [comment]
One question .... could you make the status effect of the lower token be hidden when another token overlaps? 

![2](https://user-images.githubusercontent.com/86131373/217374150-66f68e27-dfa5-43d7-a680-72d254431679.jpg)
![3](https://user-images.githubusercontent.com/86131373/217374154-32ff0196-e88d-4fac-b09b-b9d51dcf17a5.jpg)

If a token has a status effect assigned to it, it is seen on top of the overlay token. I don't know if there is a way with this module to hide it downwards as well or if it depends on the core because it being placed in the UI layer.

**Comment by xaukael** [comment]
This does nothing of what token z does, but am curious what could possibly be causing the conflict.

I do not believe those overlays are not core, so it would be up to whatever is creating them to keep them on the same level as it's parent token. I would not hold my breath for that.
